const  ARABIC_LANGUAGE = {

    //need to be translated into Arabic
    TRIGGER_FIELD_ERROR :  "-",
    NUMBER_FIELD_ERROR : "-",
    MEANING_FIELD_ERROR : "-",
    SYSTEM_FIELD_ERROR : "-",
    SUCCESS_ADD_ROW_MSG : 'הנתונים נשלחו בהצלחה',
    WAITING_BUTTON : "המתן...",
    SEND_TRIGGER_BUTTON : "שלח טריגר",
    ADD_TRIGGER_TITLE : " הוספת טריגר",
    NUMBER_FIELD : "מספר",
    TRIGGER_FIELD : "טריגר",
    SYSTEM_FIELD : "מערכת",
    MEANING_FIELD : "משמעות",
    LANGUAGE_BUTTON : "שינוי שפה",
    STATISTIC_BUTTON : "בחר סטטיסטיקת פניות להצגה",
    STATISTIC_TYPE_A_OPTION : "יומית",
    STATISTIC_TYPE_B_OPTION : "שבועית",
    STATISTIC_TYPE_C_OPTION : "חודשית",
    STATISTIC_TYPE_D_OPTION : "שנתית",
    OPEN_INQUIRIES_LABEL : "ממתינות לטיפול",
    HANDLED_ALERT_LABEL : "טופלו",
    CHART_OPTIONS_TEXT : "סטטוס פניות",
    CHART_TITLE_H2 : "פניות שטופלו",
    TOTAL_LABEL : 'סה"כ',
    LOADING_ALT : "טוען...",
    
    DELETE: "حذف",
    ADD_RANGE: "اضافة حد",
    EDIT: "تعديل",
    MESSAGE: "رسالة",
    MIN: "حد ادنى",
    MAX: "حد اعلى",
    ACTIONS: "إجراءات",
    EXPAND: "تضخيم",
    CHECKED_ITEMS: "العناصر المختارة",
    RANGES: "حدود",
    UNIT: "وحدة",
    NAME: "اسم",
    MEANING: "معنى",
    ACTIVITY: "فعليات",
    PARAMETERS: "المعاملات",
    SYSTEM_NUMBER: "رقم النظام",
    SENSORS: "حساسات",
    IDENTIFIERS: "المعرفين",
    TRIGGERS: "المؤثرات",
    CONFIG_CONDITIONS: " شروط التكوين ",
    LEVEL: "مستوى",
    VALUE_TYPE: "نوع القيمة",
    MEASURED_VALUE: "القيمة المحسوبة",
    TRIGGER_NAME: "اسم المؤثر",
    TYPE: "نوع",
    PREVIOUS_SYSTEM_ID: "رقم النظام السابق",
    SYSTEM_ID: "رقم النظام",
    CONFIG_CONDITION_ID: "معرف شرط التكوين",
    STATUS: "الوضع",
    CITY: "المدينة",
    STREET: "الشارع",
    NUMBER: "الرقم",
    LATITUDE: "خطوط الطول",
    LONGITUDE: "خطوط العرض",
    CREATED_AT: "تم إنشاؤه",
    UPDATED_AT: "تم تعديله",
    IDENTIFIER_ID: "رقم المعرف",
    ADDITIONAL_IDENTIFIER: "معرف اضافي",
    TRIGGER: "المؤثر",
    SYSTEM: "النظام",
 

}

export default ARABIC_LANGUAGE;
