const  ENGLISH_LANGUAGE = {
    TRIGGER_FIELD_ERROR :  "-",
    NUMBER_FIELD_ERROR : "-",
    MEANING_FIELD_ERROR : "-",
    SYSTEM_FIELD_ERROR : "-",
    SUCCESS_ADD_ROW_MSG : "The data sent successfully",
    WAITING_BUTTON : "Waiting...",
    SEND_TRIGGER_BUTTON : "Send trigger",
    ADD_TRIGGER_TITLE : "Add a new trigger",
    NUMBER_FIELD : "Number",
    TRIGGER_FIELD : "Trigger",
    SYSTEM_FIELD : "System",
    MEANING_FIELD : "Meaning",
    LANGUAGE_BUTTON : "Change language",
    STATISTIC_BUTTON : "Show handled inquiries:",
    STATISTIC_TYPE_A_OPTION : "Daily",
    STATISTIC_TYPE_B_OPTION : "Weekly",
    STATISTIC_TYPE_C_OPTION : "Monthly",
    STATISTIC_TYPE_D_OPTION : "Yearly",
    OPEN_INQUIRIES_LABEL : "Waiting for treatment",
    HANDLED_ALERT_LABEL : "Closed inquiries",
    CHART_OPTIONS_TEXT : "Status of inquiries",
    CHART_TITLE_H2 : "Inquiries handled",
    TOTAL_LABEL : "Total",
    LOADING_ALT : "LOADING...",


    DELETE: "Delete",
      "ADD_RANGE": "Add Range",
      EDIT: "Edit",
      MESSAGE: "Message",
      MIN: "Min",
      MAX: "Max",
      ACTIONS: "Actions",
      EXPAND: "Expand",
      CHECKED_ITEMS: "Checked Items",
      RANGES: "Ranges",
      UNIT: "Unit",
      NAME: "Name",
      MEANING: "Meaning",
      ACTIVITY: "Activity",
      PARAMETERS: "Parameters",
      Actions: "Actions",
      SYSTEM_NUMBER: "System Number",
      SENSORS: "Sensors",
      IDENTIFIERS: "Identifiers",
      TRIGGERS: "Triggers",
      CONFIG_CONDITIONS: "Config Conditions",
      LEVEL: "Level",
      VALUE_TYPE: "value Type",
      MEASURED_VALUE: "Measured Value",
      TRIGGER_TYPE:"Trigger Type",
      SENSOR_NAME:"Sensor Name",
      SENSOR_TYPE:"Sensor Type",
      TRIGGER_NAME: "Trigger Name",
      SYSTEM:"System",
      TYPE: "type",
      PREVIOUS_SYSTEM_ID: "Previous System Id",
      SYSTEM_ID: "System ID",
      CONFIG_CONDITION_ID: "config Condition ID",
      STATUS: "Status",
      CITY: "City",
      STREET: "Street",
      NUMBER: "Number",
      LATITUDE: "Latitude",
      LONGITUDE: "Longitude",
      CREATED_AT: "Created",
      UPDATED_AT: "Updated",
      IDENTIFIER_ID: "Identifier ID",
      ADDITIONAL_IDENTIFIER: "Additional Identifier",
      TRIGGER: "Trigger",



}


export default ENGLISH_LANGUAGE;
