const  HEBREW_LANGUAGE = {
    TRIGGER_FIELD_ERROR :  "-",
    NUMBER_FIELD_ERROR : "-",
    MEANING_FIELD_ERROR : "-",
    SYSTEM_FIELD_ERROR : "-",
    SUCCESS_ADD_ROW_MSG : 'הנתונים נשלחו בהצלחה',
    WAITING_BUTTON : "המתן...",
    SEND_TRIGGER_BUTTON : "שלח טריגר",
    ADD_TRIGGER_TITLE : " הוספת טריגר",
    NUMBER_FIELD : "מספר",
    TRIGGER_FIELD : "טריגר",
    SYSTEM_FIELD : "מערכת",
    MEANING_FIELD : "משמעות",
    LANGUAGE_BUTTON : "שינוי שפה",
    STATISTIC_BUTTON : "בחר סטטיסטיקת פניות להצגה",
    STATISTIC_TYPE_A_OPTION : "יומית",
    STATISTIC_TYPE_B_OPTION : "שבועית",
    STATISTIC_TYPE_C_OPTION : "חודשית",
    STATISTIC_TYPE_D_OPTION : "שנתית",
    OPEN_INQUIRIES_LABEL : "ממתינות לטיפול",
    HANDLED_ALERT_LABEL : "טופלו",
    CHART_OPTIONS_TEXT : "סטטוס פניות",
    CHART_TITLE_H2 : "פניות שטופלו",
    TOTAL_LABEL : 'סה"כ',
    LOADING_ALT : "טוען...",
    
    TRIGGERS: "טריגרים",
    CONFIG_CONDITIONS: "תנאי הגדרות ",
    CITY: "עיר",
    STREET: "רחוב ",
    NUMBER: "מספר",
    LATITUDE: "קו רוחב",
    LONGITUDE: "קו אורך",
    CREATED_AT: "נוצר בתאריך",
    UPDATED_AT: "עודכן בתאריך",
    IDENTIFIER_ID: "זיהוי",
    TRIGGER: "טריגר",
    MEANING: "משמעות",
    SYSTEM: "מערכת",
    STATUS: "מצב",
    ADDITIONAL_IDENTIFIER: "זיהוי נוסף",
    CONFIG_CONDITION_ID: "מזהה תנאי הגדרות",
    SYSTEM_ID: "מזהה המערכת",
    PREVIOUS_SYSTEM_ID: "מזהה המערכת הקודמת",
    TYPE: "סוג",
    TRIGGER_NAME: "שם הטריגר",
    VALUE_TYPE: "סוג הערך",
    MEASURED_VALUE: "ערך מודד",
    LEVEL: "רמה",
    IDENTIFIERS: "מזהים",
    SENSORS: "חיישנים ",
    SYSTEM_NUMBER: "מספר המערכת",
    ACTIONS: "פעולות",
    PARAMETERS: "פרמטרים",
    ACTIVITY: "פעילות",
    NAME: "שם",
    UNIT: "יחידה",
    RANGES: "טווחים",
    CHECKED_ITEMS: "פריטים שנבדקו",
    EXPAND: "להרחיב",
    MESSAGE: "הודעה",
    MIN: "מינימום",
    MAX: "מקסימום",
    EDIT: "לערוך",
    ADD_RANGE: "הוסף טווח",
    DELETE: "למחוק",

}

export default HEBREW_LANGUAGE;
