import { getItem } from "../services/localStorageService";
import { DEFAULT_LANGUAGE } from "../constants";

export let language = getItem("language") || DEFAULT_LANGUAGE; //set hebrew language by default

export default (word) => {
  //get the lang out of attribute as has been set in the constants/index.js file
  let lang = document.getElementsByTagName("html")[0].getAttribute("lang");

  const lookUps = {
    he: {
      TRIGGER_FIELD_ERROR: "-",
      NUMBER_FIELD_ERROR: "-",
      MEANING_FIELD_ERROR: "-",
      SYSTEM_FIELD_ERROR: "-",
      SUCCESS_ADD_ROW_MSG: "הנתונים נשלחו בהצלחה",
      WAITING_BUTTON: "המתן...",
      SEND_TRIGGER_BUTTON: "שלח טריגר",
      ADD_TRIGGER_TITLE: " הוספת טריגר",
      NUMBER_FIELD: "מספר",
      TRIGGER_FIELD: "טריגר",
      SYSTEM_FIELD: "מערכת",
      MEANING_FIELD: "משמעות",
      LANGUAGE_BUTTON: "שינוי שפה",
      STATISTIC_BUTTON: "בחר סטטיסטיקת פניות להצגה",
      STATISTIC_TYPE_A_OPTION: "יומית",
      STATISTIC_TYPE_B_OPTION: "שבועית",
      STATISTIC_TYPE_C_OPTION: "חודשית",
      STATISTIC_TYPE_D_OPTION: "שנתית",
      OPEN_INQUIRIES_LABEL: "ממתינות לטיפול",
      HANDLED_ALERT_LABEL: "טופלו",
      CHART_OPTIONS_TEXT: "סטטוס פניות",
      CHART_TITLE_H2: "פניות שטופלו",
      TOTAL_LABEL: 'סה"כ',
      LOADING_ALT: "טוען...",

      TRIGGERS: "טריגרים",
      CONFIG_CONDITIONS: "תנאי הגדרות ",
      CITY: "עיר",
      STREET: "רחוב ",
      NUMBER: "מספר",
      LATITUDE: "קו רוחב",
      LONGITUDE: "קו אורך",
      CREATED_AT: "נוצר בתאריך",
      UPDATED_AT: "עודכן בתאריך",
      IDENTIFIER_ID: "זיהוי",
      TRIGGER: "טריגר",
      MEANING: "משמעות",
      SYSTEM: "מערכת",
      STATUS: "מצב",
      ADDITIONAL_IDENTIFIER: "זיהוי נוסף",
      CONFIG_CONDITION_ID: "מזהה תנאי הגדרות",
      SYSTEM_ID: "מזהה המערכת",
      PREVIOUS_SYSTEM_ID: "מזהה המערכת הקודמת",
      TYPE: "סוג",
      TRIGGER_NAME: "שם הטריגר",
      VALUE_TYPE: "סוג הערך",
      MEASURED_VALUE: "ערך מודד",
      LEVEL: "רמה",
      IDENTIFIERS: "מזהים",
      SENSORS: "חיישנים ",
      SYSTEM_NUMBER: "מספר המערכת",
      ACTIONS: "פעולות",
      PARAMETERS: "פרמטרים",
      ACTIVITY: "פעילות",
      NAME: "שם",
      UNIT: "יחידה",
      RANGES: "טווחים",
      CHECKED_ITEMS: "פריטים שנבדקו",
      EXPAND: "להרחיב",
      MESSAGE: "הודעה",
      MIN: "מינימום",
      MAX: "מקסימום",
      EDIT: "לערוך",
      ADD_RANGE: "הוסף טווח",
      DELETE: "למחוק",
    },
    en: {
      TRIGGER_FIELD_ERROR: "-",
      NUMBER_FIELD_ERROR: "-",
      MEANING_FIELD_ERROR: "-",
      SYSTEM_FIELD_ERROR: "-",
      SUCCESS_ADD_ROW_MSG: "The data sent successfully",
      WAITING_BUTTON: "Waiting...",
      SEND_TRIGGER_BUTTON: "Send trigger",
      ADD_TRIGGER_TITLE: "Add a new trigger",
      NUMBER_FIELD: "Number",
      TRIGGER_FIELD: "Trigger",
      SYSTEM_FIELD: "System",
      MEANING_FIELD: "Meaning",
      LANGUAGE_BUTTON: "Change language",
      STATISTIC_BUTTON: "Show handled inquiries:",
      STATISTIC_TYPE_A_OPTION: "Daily",
      STATISTIC_TYPE_B_OPTION: "Weekly",
      STATISTIC_TYPE_C_OPTION: "Monthly",
      STATISTIC_TYPE_D_OPTION: "Yearly",
      OPEN_INQUIRIES_LABEL: "Waiting for treatment",
      HANDLED_ALERT_LABEL: "Closed inquiries",
      CHART_OPTIONS_TEXT: "Status of inquiries",
      CHART_TITLE_H2: "Inquiries handled",
      TOTAL_LABEL: "Total",
      LOADING_ALT: "LOADING...",

      DELETE: "Delete",
      ADD_RANGE: "Add Range",
      EDIT: "Edit",
      MESSAGE: "Message",
      MIN: "Min",
      MAX: "Max",
      ACTIONS: "Actions",
      EXPAND: "Expand",
      CHECKED_ITEMS: "Checked Items",
      RANGES: "Ranges",
      UNIT: "Unit",
      NAME: "Name",
      MEANING: "Meaning",
      ACTIVITY: "Activity",
      PARAMETERS: "Parameters",
      Actions: "Actions",
      SYSTEM_NUMBER: "System Number",
      SENSORS: "Sensors",
      IDENTIFIERS: "Identifiers",
      TRIGGERS: "Triggers",
      CONFIG_CONDITIONS: "Config Conditions",
      LEVEL: "Level",
      VALUE_TYPE: "value Type",
      MEASURED_VALUE: "Measured Value",
      TRIGGER_TYPE: "Trigger Type",
      SENSOR_NAME: "Sensor Name",
      SENSOR_TYPE: "Sensor Type",
      TRIGGER_NAME: "Trigger Name",
      SYSTEM: "System",
      TYPE: "type",
      PREVIOUS_SYSTEM_ID: "Previous System Id",
      SYSTEM_ID: "System ID",
      CONFIG_CONDITION_ID: "config Condition ID",
      STATUS: "Status",
      CITY: "City",
      STREET: "Street",
      NUMBER: "Number",
      LATITUDE: "Latitude",
      LONGITUDE: "Longitude",
      CREATED_AT: "Created",
      UPDATED_AT: "Updated",
      IDENTIFIER_ID: "Identifier ID",
      ADDITIONAL_IDENTIFIER: "Additional Identifier",
      TRIGGER: "Trigger",
    },
    ar: {
      //need to be translated into Arabic
      TRIGGER_FIELD_ERROR: "-",
      NUMBER_FIELD_ERROR: "-",
      MEANING_FIELD_ERROR: "-",
      SYSTEM_FIELD_ERROR: "-",
      SUCCESS_ADD_ROW_MSG: "הנתונים נשלחו בהצלחה",
      WAITING_BUTTON: "המתן...",
      SEND_TRIGGER_BUTTON: "שלח טריגר",
      ADD_TRIGGER_TITLE: " הוספת טריגר",
      NUMBER_FIELD: "מספר",
      TRIGGER_FIELD: "טריגר",
      SYSTEM_FIELD: "מערכת",
      MEANING_FIELD: "משמעות",
      LANGUAGE_BUTTON: "שינוי שפה",
      STATISTIC_BUTTON: "בחר סטטיסטיקת פניות להצגה",
      STATISTIC_TYPE_A_OPTION: "יומית",
      STATISTIC_TYPE_B_OPTION: "שבועית",
      STATISTIC_TYPE_C_OPTION: "חודשית",
      STATISTIC_TYPE_D_OPTION: "שנתית",
      OPEN_INQUIRIES_LABEL: "ממתינות לטיפול",
      HANDLED_ALERT_LABEL: "טופלו",
      CHART_OPTIONS_TEXT: "סטטוס פניות",
      CHART_TITLE_H2: "פניות שטופלו",
      TOTAL_LABEL: 'סה"כ',
      LOADING_ALT: "טוען...",

      DELETE: "حذف",
      ADD_RANGE: "اضافة حد",
      EDIT: "تعديل",
      MESSAGE: "رسالة",
      MIN: "حد ادنى",
      MAX: "حد اعلى",
      ACTIONS: "إجراءات",
      EXPAND: "تضخيم",
      CHECKED_ITEMS: "العناصر المختارة",
      RANGES: "حدود",
      UNIT: "وحدة",
      NAME: "اسم",
      MEANING: "معنى",
      ACTIVITY: "فعليات",
      PARAMETERS: "المعاملات",
      SYSTEM_NUMBER: "رقم النظام",
      SENSORS: "حساسات",
      IDENTIFIERS: "المعرفين",
      TRIGGERS: "المؤثرات",
      CONFIG_CONDITIONS: " شروط التكوين ",
      LEVEL: "مستوى",
      VALUE_TYPE: "نوع القيمة",
      MEASURED_VALUE: "القيمة المحسوبة",
      TRIGGER_NAME: "اسم المؤثر",
      TYPE: "نوع",
      PREVIOUS_SYSTEM_ID: "رقم النظام السابق",
      SYSTEM_ID: "رقم النظام",
      CONFIG_CONDITION_ID: "معرف شرط التكوين",
      STATUS: "الوضع",
      CITY: "المدينة",
      STREET: "الشارع",
      NUMBER: "الرقم",
      LATITUDE: "خطوط الطول",
      LONGITUDE: "خطوط العرض",
      CREATED_AT: "تم إنشاؤه",
      UPDATED_AT: "تم تعديله",
      IDENTIFIER_ID: "رقم المعرف",
      ADDITIONAL_IDENTIFIER: "معرف اضافي",
      TRIGGER: "المؤثر",
      SYSTEM: "النظام",
    },
  };
  ////if set lang is not supported do back to hebrew///
  if (!lookUps[lang]) lang = "he";

  if (!lookUps[lang][word]) {
    return "translation error";
  }
  return lookUps[lang][word];
};

export const setLanguage = (lang = "he") => {
  if (lang === "he") {
    document.getElementsByTagName("html")[0].setAttribute("dir", "rtl");
  } else if (lang === "en") {
    document.getElementsByTagName("html")[0].setAttribute("dir", "ltr");
  } else if (lang === "ar") {
    document.getElementsByTagName("html")[0].setAttribute("dir", "rtl");
  }

  document.getElementsByTagName("html")[0].setAttribute("lang", lang);
  language = lang;
};
setLanguage(language);
