export const ALERT_ACTIONS = {
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT'
};

export const STATISTICS_ACTIONS = {
  // GET_HANDLED_ALERT_DAILY: 'GET_HANDLED_ALERT_DAILY',
  // GET_HANDLED_ALERT_WEEKLY: 'GET_HANDLED_ALERT_WEEKLY',
  // GET_HANDLED_ALERT_MONTHLY:'GET_HANDLED_ALERT_MONTHLY',
  // GET_HANDLED_ALERT_YEARLY: 'GET_HANDLED_ALERT_YEARLY',
  GET_HANDLED_ALERT: "GET_HANDLED_ALERT",
  SET_LOADING: 'SET_LOADING',
  STOP_LOADING:'STOP_LOADING'
};